Upgrade goreleaser to version 2
ubccr/mokey pull request #151
Opened 2024-11-24 02:51 UTC by cmd-ntrf

- Specify version number of goreleaser - 2.
- Replace deprecated `archive.replacements` by refactoring the `name_template`. [deprecation notice](https://goreleaser.com/deprecations/#archivesreplacements)
- Apply same template to nfpms file_name_templates. [deprecation notice](https://goreleaser.com/deprecations/#snapshotname_template)

2024-12-10 15:09 UTC, aebruno requested changes
@cmd-ntrf This looks great, thanks for the PR. One minor change relating to the debian package naming but otherwise looks good.

2024-12-10 15:09 UTC, aebruno commented on .goreleaser.yaml
> -        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
Debian packages have the `<DebianPackageName>_<VersionNumber>-<DebianRevisionNumber>_<DebianArchitecture>.deb ` naming convention. So let's revert this back to what it was before. Debian arch's are amd64 and arm64:

```
file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
```

2024-12-17 15:41 UTC, cmd-ntrf commented
@aebruno I have made the proposed change for deb package.

2025-05-01 00:17 UTC, aebruno approved these changes

2025-05-01 00:18 UTC, merged